import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ActivityStep, Question } from '../../../types';
import { ChevronLeft, ChevronRight, Clock, Eye, Star, X } from 'lucide-react';
import confetti from 'canvas-confetti';
import InteractiveGameEngine from '../../activities/InteractiveGameEngine';

interface Props { activity: Activity | null; questions: Question[]; onClose: () => void; }
export default function InteractiveActivityPreviewModal({activity,questions,onClose}:Props){
 const steps=useMemo<ActivityStep[]>(()=>{if(!activity)return[];return activity.steps?.length?activity.steps:(activity.questionIds||[]).map((id,i)=>({id:`legacy-${i}`,type:'question' as const,questionId:id}))},[activity]);
 const [index,setIndex]=useState(0),[completed,setCompleted]=useState(false),[score,setScore]=useState(0),[stars,setStars]=useState(0),[seconds,setSeconds]=useState((activity?.durationMinutes||5)*60);
 useEffect(()=>{setIndex(0);setCompleted(false);setScore(0);setStars(0);setSeconds((activity?.durationMinutes||5)*60)},[activity]);
 useEffect(()=>{if(!activity||activity.timerEnabled===false||completed)return;const id=window.setInterval(()=>setSeconds(v=>Math.max(0,v-1)),1000);return()=>window.clearInterval(id)},[activity,completed]);
 if(!activity)return null; const step=steps[index]; const question=step?.questionId?questions.find(q=>q.id===step.questionId):step?.gameTask?.questionId?questions.find(q=>q.id===step.gameTask?.questionId):undefined;
 const complete=(points=20)=>{if(completed)return;setCompleted(true);setScore(v=>v+points);setStars(v=>Math.min(3,v+1))};
 const next=()=>{if(!completed)return;if(index+1<steps.length){setIndex(v=>v+1);setCompleted(false);return;}confetti({particleCount:120,spread:80,origin:{y:.65}});onClose()};
 return <div className="fixed inset-0 z-[180] bg-stone-950/80 backdrop-blur-md flex items-center justify-center p-2 sm:p-5" onMouseDown={onClose}><div className="w-full max-w-5xl h-[96vh] bg-white rounded-[2rem] shadow-2xl overflow-hidden flex flex-col" onMouseDown={e=>e.stopPropagation()}>
 <header className="px-5 py-4 bg-stone-950 text-white flex items-center justify-between"><div className="min-w-0"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-amber-300"><Eye className="w-4 h-4"/> Game Preview · {activity.id}</div><h2 className="font-black text-xl truncate">{activity.title}</h2><div className="text-[10px] text-stone-300">{(activity.grades||[activity.grade]).join(', ')} · {activity.subject} · {activity.format||'game'}</div></div><div className="flex items-center gap-3"><span className="hidden sm:inline-flex items-center gap-1 font-black"><Star className="w-4 h-4 text-amber-300"/>{score}</span>{activity.timerEnabled!==false&&<span className="text-xs font-black inline-flex items-center gap-1"><Clock className="w-4 h-4"/>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span>}<button onClick={onClose} className="p-2 rounded-xl hover:bg-white/10"><X/></button></div></header>
 <div className="h-2 bg-stone-200"><div className="h-full bg-amber-400 transition-all" style={{width:`${steps.length?((index+1)/steps.length)*100:0}%`}}/></div>
 <main className="flex-1 overflow-y-auto p-4 sm:p-8 bg-gradient-to-b from-white to-stone-50">{step?.type==='game_task'&&step.gameTask?<InteractiveGameEngine task={step.gameTask} question={question} done={completed} onComplete={complete} preview/>:<QuestionStep question={question} done={completed} onComplete={complete}/>}</main>
 <footer className="px-5 py-4 border-t border-stone-200 flex items-center justify-between"><div className="text-xs font-black text-stone-500">Challenge {index+1} of {steps.length} · ⭐ {stars}/3</div><div className="flex gap-2"><button onClick={()=>setIndex(v=>Math.max(0,v-1))} disabled={index===0} className="px-4 py-2 rounded-xl border border-stone-200 font-bold disabled:opacity-30 inline-flex items-center gap-1"><ChevronLeft className="w-4 h-4"/>Back</button><button onClick={next} disabled={!completed} className="px-5 py-2.5 rounded-xl bg-stone-950 text-white font-black disabled:opacity-30 inline-flex items-center gap-1">{index+1<steps.length?'Next Challenge':'Finish Game'}<ChevronRight className="w-4 h-4"/></button></div></footer>
 </div></div>
}
function QuestionStep({question,done,onComplete}:{question?:Question;done:boolean;onComplete:(points?:number)=>void}){const [selected,setSelected]=useState<number|null>(null);if(!question)return <div className="p-10 text-center text-stone-500">Question Bank item not found.</div>;return <div className="max-w-3xl mx-auto text-center"><div className="text-7xl">🧠</div><h3 className="text-3xl font-black mt-3">Solve the challenge</h3><div className="mt-6 p-6 rounded-3xl bg-white border border-stone-200"><div className="text-2xl font-black">{question.prompt}</div><div className="grid grid-cols-2 gap-3 mt-6">{question.options.map((o,i)=><button key={i} disabled={done} onClick={()=>{setSelected(i);if(i===question.correctIndex)onComplete(question.points||20)}} className={`p-5 rounded-2xl border-2 font-black ${selected===i?(i===question.correctIndex?'border-emerald-500 bg-emerald-50':'border-rose-400 bg-rose-50'):'border-stone-200 hover:border-amber-400'}`}>{o}</button>)}</div></div></div>}
